### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ChadiHelwe** [jifan-chen/QA-Verification-Via-NLI#1]
Hello,

I am running your code as it is on a WSL Ubuntu. 

I am getting this error ModuleNotFoundError: No module named 'seq2seq_converter.utils'; 'seq2seq_converter' is not a package

You should move the *.sh files outside of the seq2seq_converter folder.

**Comment by jifan-chen** [comment]
You can run the script outside of the folder.
