### ISSUE TITLE
Path to Pretrained Question Convertor Unavailable

### ISSUE THREAD

**Issue by brihijoshi** [jifan-chen/QA-Verification-Via-NLI#2]
Hi!

I was trying to run the pretrained question convertor, however,  the Google Drive link for the model (give here - https://github.com/jifan-chen/QA-Verification-Via-NLI/blob/master/seq2seq_converter/run_question_converter.sh#L5) is not available. Could you please fix this link?

Thanks!

**Comment by jifan-chen** [comment]
Sorry for not cleaning that [line 5], but the actual model is downloaded by [line 23](https://github.com/jifan-chen/QA-Verification-Via-NLI/blob/master/seq2seq_converter/run_question_converter.sh#L23). If you only want to download the model, you can simply replace ${question_converter_path} to your model directory.
